@url = http://localhost:4866


### GET BASE
{{url}}

### GET BOOKS
GET {{url}}/books


### GET BOOK
GET {{url}}/book/63ffa18a3eb11c75c87b60c8


### PATCH BOOK
PATCH {{url}}/book/63ff9e0fa1bd080b7165c8e1
content-type: application/json

{
"title": "Semiotics for Beginners222",
"description": "Semiotics is a fascinating topic that goes beyond and combines linguistics, cultural anthropology, social psychology, history, art, and philosophy. It's the study of symbols and signs, or as Locke said, \"the study of all that can fall within the compass of human understanding\". This book by Daniel Chandler is [accessible online](http://visual-memory.co.uk/daniel/Documents/S4B) for free.",
"imageUrl": "http://edwardtanguay.vercel.app/share/images/books/semiotics.png",
"buyUrl": "http://visual-memory.co.uk/daniel/Documents/S4B/"
}

### POST BOOK
POST {{url}}/book/
content-type: application/json

{
"title": "الرحيق المختوم",
"description": "Semiotics is a fascinating topic that goes beyond and combines linguistics, cultural anthropology, social psychology, history, art, and philosophy. It's the study of symbols and signs, or as Locke said, \"the study of all that can fall within the compass of human understanding\". This book by Daniel Chandler is [accessible online](http://visual-memory.co.uk/daniel/Documents/S4B) for free.",
"imageUrl": "http://edwardtanguay.vercel.app/share/images/books/semiotics.png",
"buyUrl": "http://visual-memory.co.uk/daniel/Documents/S4B/",
"language":"arabic"
}


### DELETE BOOK
DELETE {{url}}/book/63ffa18a3eb11c75c87b60c8

